<a href="https://colab.research.google.com/github/bhumika-aiml/AgriCare-CS50P/blob/main/task3_pythondev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

folder = '/content/drive/MyDrive/task3-pythondev'
os.makedirs(folder, exist_ok=True)

print("Folder created successfully!")

Folder created successfully!

In [ ]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Rahul", "Sneha", "Aman", "Priya", "Rahul", None],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR", "IT", "Finance"],
    "Age": [21, 22, 20, 25, 21, None, 20, 24],
    "Salary": [35000, 30000, 40000, 45000, 35000, 32000, -5000, 45000],
    "City": ["Delhi", "Mumbai", "Delhi", "Bhopal", "Delhi", "Mumbai", "Delhi", "Bhopal"]
}

df = pd.DataFrame(data)

csv_path = '/content/drive/MyDrive/task3-pythondev/employees.csv'
df.to_csv(csv_path, index=False)

print("employees.csv saved successfully!")

employees.csv saved successfully!

In [ ]:
df = pd.read_csv(csv_path)
display(df)

    Name Department   Age  Salary    City
0   Aman         IT  21.0   35000   Delhi
1   Riya         HR  22.0   30000  Mumbai
2  Rahul         IT  20.0   40000   Delhi
3  Sneha    Finance  25.0   45000  Bhopal
4   Aman         IT  21.0   35000   Delhi
5  Priya         HR   NaN   32000  Mumbai
6  Rahul         IT  20.0   -5000   Delhi
7    NaN    Finance  24.0   45000  Bhopal

In [ ]:

data = {
    "Name": ["Aman", "Riya", "Rahul", "Sneha", "Aman", "Priya", "Rahul", None],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR", "IT", "Finance"],
    "Age": [21, 22, 20, 25, 21, None, 20, 24],
    "Salary": [35000, 30000, 40000, 45000, 35000, 32000, -5000, 45000],
    "City": ["Delhi", "Mumbai", "Delhi", "Bhopal", "Delhi", "Mumbai", "Delhi", "Bhopal"]
}

df = pd.DataFrame(data)

df.to_csv("employees.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [ ]:
df = pd.read_csv("employees.csv")

display(df)

    Name Department   Age  Salary    City
0   Aman         IT  21.0   35000   Delhi
1   Riya         HR  22.0   30000  Mumbai
2  Rahul         IT  20.0   40000   Delhi
3  Sneha    Finance  25.0   45000  Bhopal
4   Aman         IT  21.0   35000   Delhi
5  Priya         HR   NaN   32000  Mumbai
6  Rahul         IT  20.0   -5000   Delhi
7    NaN    Finance  24.0   45000  Bhopal

In [ ]:
print(df.isnull().sum())

Name          1
Department    0
Age           1
Salary        0
City          0
dtype: int64

In [ ]:
df = df.dropna(subset=["Name"])
df["Age"] = df["Age"].fillna(df["Age"].median())
print(df.isnull().sum())

Name          0
Department    0
Age           0
Salary        0
City          0
dtype: int64

In [ ]:
print(df)

    Name Department   Age  Salary    City
0   Aman         IT  21.0   35000   Delhi
1   Riya         HR  22.0   30000  Mumbai
2  Rahul         IT  20.0   40000   Delhi
3  Sneha    Finance  25.0   45000  Bhopal
4   Aman         IT  21.0   35000   Delhi
5  Priya         HR  21.0   32000  Mumbai
6  Rahul         IT  20.0   -5000   Delhi

In [ ]:
it_employees = df[df["Department"] == "IT"]

print(it_employees)

    Name Department   Age  Salary   City
0   Aman         IT  21.0   35000  Delhi
2  Rahul         IT  20.0   40000  Delhi
4   Aman         IT  21.0   35000  Delhi
6  Rahul         IT  20.0   -5000  Delhi

In [ ]:
high_salary = df[df["Salary"] > 35000]

print(high_salary)

    Name Department   Age  Salary    City
2  Rahul         IT  20.0   40000   Delhi
3  Sneha    Finance  25.0   45000  Bhopal

In [ ]:
delhi_employees = df[df["City"] == "Delhi"]

print(delhi_employees)

    Name Department   Age  Salary   City
0   Aman         IT  21.0   35000  Delhi
2  Rahul         IT  20.0   40000  Delhi
4   Aman         IT  21.0   35000  Delhi
6  Rahul         IT  20.0   -5000  Delhi

In [ ]:
department_group = df.groupby("Department")

print(department_group["Salary"].mean())

Department
Finance    45000.0
HR         31000.0
IT         26250.0
Name: Salary, dtype: float64

In [ ]:
summary = df.groupby("Department")["Salary"].agg(
    ["count", "mean", "min", "max"]
)

print(summary)

            count     mean    min    max
Department
Finance         1  45000.0  45000  45000
HR              2  31000.0  30000  32000
IT              4  26250.0  -5000  40000

In [ ]:
avg_salary = df.groupby("Department")["Salary"].mean()

print("Average Salary by Department:")
print(avg_salary)

Average Salary by Department:
Department
Finance    45000.0
HR         31000.0
IT         26250.0
Name: Salary, dtype: float64

In [ ]:
print("Average Age:", df["Age"].mean())

Average Age: 21.428571428571427

In [ ]:
print(df["Department"].value_counts())

Department
IT         4
HR         2
Finance    1
Name: count, dtype: int64

In [ ]:
print("Cleaned Dataset:")
display(df)

Cleaned Dataset:

    Name Department   Age  Salary    City
0   Aman         IT  21.0   35000   Delhi
1   Riya         HR  22.0   30000  Mumbai
2  Rahul         IT  20.0   40000   Delhi
3  Sneha    Finance  25.0   45000  Bhopal
4   Aman         IT  21.0   35000   Delhi
5  Priya         HR  21.0   32000  Mumbai
6  Rahul         IT  20.0   -5000   Delhi

In [ ]:
df.to_csv("cleaned_employees.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

The dataset was analyzed using Pandas. Missing values were identified and handled, while incorrect salary values were removed. The data was filtered based on department, salary, and city. Grouping and aggregation were used to calculate department-wise employee counts and average salaries. The analysis helps understand salary patterns and employee distribution across departments